wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1653062721
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      4: 3.9.2
      5: 0.12.14
      8:
      - 5
batchsize_discriminator:
  desc: null
  value: 512
env_id:
  desc: null
  value: randomized_v3
gamma:
  desc: null
  value: 0.999
