# SETTINGS MORL
# it has to be : len(ppo_files) = len(discriminator_files) = len(ratio)-1


# Truc qui sont pas ammenés à changer
model_path: "saved_models/"
demo_path: "demonstrations/"
model_ext: ".pt"
demo_ext: ".pk"
env_rad: "randomized_"
ppo_filenames: "ppo_"
discriminator_filenames: "discriminator_"


# Editable parameters
env: "v3"
nb_experts: 2
experts_weights: [[1,1,0,1], [0,1,1,1]]
ratio: [0, 1, 1]
#nb_demos: 1000
nb_demos: 100
